### ISSUE TITLE
Getting an exception on blank API responses

### ISSUE THREAD

**Issue by KevinBacas** [restackcloud/restack.js#1]
**It's not blocking or urgent to fix it, but we need to get rid of it at some point**

We're getting an error on blank API reponses `error: [SyntaxError: Unexpected end of input]`. This is obviously throwing an exception but I can't figure out a way of handling it. I guess it's when the Promise is trying to parse the body of the response.

Example:
**Destroy an Application**

Example Request:
```
DELETE /v1/apps/example-go/ HTTP/1.1
Host: deis.example.com
Authorization: token abc123
```

Example Response:
```
HTTP/1.1 204 NO CONTENT
DEIS_API_VERSION: 1.7
DEIS_PLATFORM_VERSION: 1.12.2
```

**Comment by KevinBacas** [comment]
Concerning isomorphic-fetch, a few months ago, they updated to the latest version of WHATWG Fetch API. We should try out [v2.2.1](https://github.com/matthew-andrews/isomorphic-fetch/releases/tag/v2.2.1) of isomorphic fetch. We might also try out the [latest version](https://github.com/stefanpenner/es6-promise/releases/tag/v3.2.1) of es6-promise.

**Comment by MaxenceAdnot** [comment]
We should also see if the v2 api still reproduce this behavior

**Comment by KevinBacas** [comment]
V2 didn't solve this issue. They still send blank API responses.. (*Destroy an application* for instance)

Currently, the bug is handled in our front-end, but it would be perfect to fix it in restack.js's core :)

Kévin BACAS
3A Informatique, majeure monétique et sécurité informatique - ENSICAEN
M2 Administration des Entreprises - IAE de Caen
