### ISSUE TITLE
Cannot get error message

### ISSUE THREAD

**Issue by KevinBacas** [restackcloud/restack.js#2]
I need to change the **checkStatus function** in order to retrieve the error message. I'm currently just returning the statusText but I also need the response body to display the message to the end-user.

**Comment by KevinBacas** [comment]
Thowing an exception isn't the right way to handle errors. I cannot get errors messages this way. I'll try changing the core logic and just call the right callback depending on the responseCode

**Comment by MaxenceAdnot** [comment]
Actually throwing exception is the correct way to handle exceptions ;)

**Comment by warriorx51** [comment]
throwing smoke on B to get error code would be more appropriate. Drop me awp please.

**Comment by KevinBacas** [comment]
"**Thowing an exception** isn't the right way to handle **errors**."

There's a difference between "errors" and "exceptions". An exception is cutting the program off so I can't read anything from the response. In this case, I need to return the response content. So obviously here, it's not  the correct way to do it. :disappointed:

**Comment by MaxenceAdnot** [comment]
So, imo, it has more to do with a conception and design problem than with exception cutting the program off :)

**Comment by KevinBacas** [comment]
That's why I said that throwing exceptions isn't the right way to handle errors here. You don't want the promise to stop processing the request. You want it to handle the error, process it and then send data to the callback.

**Comment by KevinBacas** [comment]
We can catch errors using an RxJS layer on top of isomorphic-fetch. See demo attached. I made it with jquery's promises but i should work as well with isomorphic-fetch.

Link #3 for RxJS.

![capture](https://cloud.githubusercontent.com/assets/1434393/14381821/915d5ade-fd89-11e5-91d6-f13a5c4117b1.PNG)

**Comment by KevinBacas** [comment]
Fixed with 79ad4719c4fac75b825b6ce428a5caf3a47d9116
